repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0 # Use the latest release version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 21.12b0 # Use the latest release version
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1 # Use the latest release version
    hooks:
      - id: flake8
